name: deploy-to-docker.io
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  # Run all unit tests.
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Build with Maven
        run: mvn -B package --file pom.xml
