name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '16'
          cache: 'maven'

      - name: mvn deploy
        run: mvn -B deploy -DskipTests=true --file pom.xml
